server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blood-stats
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
application:
  supplies-in-PL-url: https://krew.info/zapasy/
